# Generated by Django 2.0 on 2018-01-19 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aukcje', '0003_auto_20180119_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komentarz',
            name='aukcja',
        ),
        migrations.AlterField(
            model_name='komentarz',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
